name: thesisapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_bottom_navigation_bar: ^1.3.3
  material_symbols_icons: ^4.2719.3
  flutter_echarts: ^2.5.0
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.10
  flutter_reactive_ble: ^5.3.1
  sprintf: ^7.0.0
  permission_handler: ^11.3.1
  simple_logger: ^1.9.0+2
  provider: ^6.0.5
  flutter_spinkit: ^5.2.0
  real_time_chart: ^0.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Black.ttf
          weight: 900
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Thin.ttf
          weight: 100