// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIKqrZdE5yKyoioWx2Cn3vYPDEjixTtOY ',
    appId: '1:1027919477795:android:494a84a7de20f5a3a14596',
    messagingSenderId: '1027919477795',
    projectId: 'thesisapp-a705d',
    authDomain: 'quickstart-flutter.firebaseapp.com',
    storageBucket: 'com.example.thesisapp',
    measurementId: 'G-VZRVEJTBVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIKqrZdE5yKyoioWx2Cn3vYPDEjixTtOY ',
    appId: '1:1027919477795:android:494a84a7de20f5a3a14596',
    messagingSenderId: '1027919477795',
    projectId: 'thesisapp-a705d',
    storageBucket: 'com.example.thesisapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIKqrZdE5yKyoioWx2Cn3vYPDEjixTtOY ',
    appId: '1:1027919477795:android:494a84a7de20f5a3a14596',
    messagingSenderId: '1027919477795 ',
    projectId: 'fthesisapp-a705d',
    storageBucket: 'com.example.thesisapp',
    iosClientId: '879683392852-033rm5j7vc5spd6frsolbs4g8jqfd7jg.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIKqrZdE5yKyoioWx2Cn3vYPDEjixTtOY ',
    appId: '1:1027919477795:android:494a84a7de20f5a3a14596',
    messagingSenderId: '1027919477795 ',
    projectId: 'thesisapp-a705d',
    storageBucket: 'com.example.thesisapp',
    iosClientId: '879683392852-033rm5j7vc5spd6frsolbs4g8jqfd7jg.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );
}
