// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIw6HKVLtAjLem9AWiQKjWxMLNx3BiVGk ',
    appId: '1:1019029182920:android:bfe14c8d2ef1a0b62348fd',
    messagingSenderId: '1019029182920',
    projectId: 'flash-chat-e86ff',
    authDomain: 'quickstart-flutter.firebaseapp.com',
    storageBucket: 'com.JonathanSonnen.flash_chat',
    measurementId: 'G-VZRVEJTBVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIw6HKVLtAjLem9AWiQKjWxMLNx3BiVGk ',
    appId: '1:1019029182920:android:bfe14c8d2ef1a0b62348fd',
    messagingSenderId: '1019029182920',
    projectId: 'flash-chat-e86ff',
    storageBucket: 'com.JonathanSonnen.flash_chat',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIw6HKVLtAjLem9AWiQKjWxMLNx3BiVGk ',
    appId: '1:1019029182920:android:bfe14c8d2ef1a0b62348fd',
    messagingSenderId: '1019029182920 ',
    projectId: 'flash-chat-e86ff',
    storageBucket: 'com.JonathanSonnen.flash_chat',
    iosClientId: '879683392852-033rm5j7vc5spd6frsolbs4g8jqfd7jg.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIw6HKVLtAjLem9AWiQKjWxMLNx3BiVGk ',
    appId: '1:1019029182920:android:bfe14c8d2ef1a0b62348fd',
    messagingSenderId: '1019029182920 ',
    projectId: 'quickstart-flutter',
    storageBucket: 'com.JonathanSonnen.flash_chat',
    iosClientId: '879683392852-033rm5j7vc5spd6frsolbs4g8jqfd7jg.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );
}
